FROM ubuntu:22.04

# This is the base image used to build all the cross-compiler toolchains and libraries.
# It is based on Ubuntu 22.04 LTS and includes all the necessary dependencies to build.

ENV TZ=Europe/Rome
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y build-essential cmake dh-autoreconf git gperf pkg-config tar bison flex unzip curl wget

CMD ["bash"]
